"""Initial migration

Revision ID: 48dc18cb8cda
Revises: 
Create Date: 2025-05-15 14:09:21.893747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48dc18cb8cda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'leader', 'subleader', 'member', name='role'), nullable=False),
    sa.Column('learning', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.JSON(), nullable=True),
    sa.Column('period_task_score', sa.Integer(), nullable=True),
    sa.Column('below_average_flag', sa.Boolean(), nullable=False),
    sa.Column('below_average_last_check', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id', 'email'),
    sa.UniqueConstraint('id', 'phone'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.Enum('DAILY_TASK_CREATED', 'DAILY_REPORT_REMINDER', name='notificationtype'), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('period_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('assigner_id', sa.String(length=20), nullable=False),
    sa.Column('assignee_id', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('basic_task_requirements', sa.Text(), nullable=False),
    sa.Column('detail_task_requirements', sa.Text(), nullable=False),
    sa.Column('completed_task_description', sa.Text(), nullable=True),
    sa.Column('task_review', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['assigner_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['members.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period_tasks')
    op.drop_table('notifications')
    op.drop_table('members')
    op.drop_table('departments')
    # ### end Alembic commands ###
